package com.leb.app.domain.enumeration;

/**
 * The Status enumeration.
 */
public enum Status {
    WAITING,
    OPENED,
    OPENING,
    COMPLETING,
    COMPLETED,
    REFUSING,
    REFUSED,
    PENDING,
    CLOSING,
    CLOSED,
    IN_PROGRESS,
    PROCESSING,
    PROCESSED,
    PRE_PROCESSING,
    PRE_PROCESSED,
    LOSTED,
    CHECKING,
    CHECKED,
    CANCELED,
    CANCELING,
    DENIED,
    FAIL,
    INCOMPLET,
    SHIPPED,
    IN_TRANSIT,
    WAITING_COLLECTION,
    WAITING_COLLECTION_ACCEPTED,
    IN_COLLECTION,
    WAITING_TRANSIT,
    WAITING_TRANSIT_ACCEPTED,
    WAITING_DISTRIBUTION,
    WAITING_DISTRIBUTION_ACCEPTED,
    IN_DISTRIBUTION,
    REJECTED,
    FINISHED
}
