export enum Status {
  WAITING = 'WAITING',

  OPENED = 'OPENED',

  OPENING = 'OPENING',

  COMPLETING = 'COMPLETING',

  COMPLETED = 'COMPLETED',

  REFUSING = 'REFUSING',

  REFUSED = 'REFUSED',

  PENDING = 'PENDING',

  CLOSING = 'CLOSING',

  CLOSED = 'CLOSED',

  IN_PROGRESS = 'IN_PROGRESS',

  PROCESSING = 'PROCESSING',

  PROCESSED = 'PROCESSED',

  PRE_PROCESSING = 'PRE_PROCESSING',

  PRE_PROCESSED = 'PRE_PROCESSED',

  LOSTED = 'LOSTED',

  CHECKING = 'CHECKING',

  CHECKED = 'CHECKED',

  CANCELED = 'CANCELED',

  CANCELING = 'CANCELING',

  DENIED = 'DENIED',

  FAIL = 'FAIL',

  INCOMPLET = 'INCOMPLET',

  SHIPPED = 'SHIPPED',

  IN_TRANSIT = 'IN_TRANSIT',

  WAITING_COLLECTION = 'WAITING_COLLECTION',

  WAITING_COLLECTION_ACCEPTED = 'WAITING_COLLECTION_ACCEPTED',

  IN_COLLECTION = 'IN_COLLECTION',

  WAITING_TRANSIT = 'WAITING_TRANSIT',

  WAITING_TRANSIT_ACCEPTED = 'WAITING_TRANSIT_ACCEPTED',

  WAITING_DISTRIBUTION = 'WAITING_DISTRIBUTION',

  WAITING_DISTRIBUTION_ACCEPTED = 'WAITING_DISTRIBUTION_ACCEPTED',

  IN_DISTRIBUTION = 'IN_DISTRIBUTION',

  REJECTED = 'REJECTED',

  FINISHED = 'FINISHED',
}
